# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

steps:
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Azure for Students(c0f87bca-394b-46e7-98d3-31e177e2d273)'
    azureContainerRegistry: '{"loginServer":"bolsadetrabajocontainerregistry.azurecr.io", "id" : "/subscriptions/c0f87bca-394b-46e7-98d3-31e177e2d273/resourceGroups/bolsa-de-trabajo/providers/Microsoft.ContainerRegistry/registries/BolsaDeTrabajoContainerRegistry"}'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Build services'
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Azure for Students(c0f87bca-394b-46e7-98d3-31e177e2d273)'
    azureContainerRegistry: '{"loginServer":"bolsadetrabajocontainerregistry.azurecr.io", "id" : "/subscriptions/c0f87bca-394b-46e7-98d3-31e177e2d273/resourceGroups/bolsa-de-trabajo/providers/Microsoft.ContainerRegistry/registries/BolsaDeTrabajoContainerRegistry"}'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Push services'
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Azure for Students(c0f87bca-394b-46e7-98d3-31e177e2d273)'
    azureContainerRegistry: '{"loginServer":"bolsadetrabajocontainerregistry.azurecr.io", "id" : "/subscriptions/c0f87bca-394b-46e7-98d3-31e177e2d273/resourceGroups/bolsa-de-trabajo/providers/Microsoft.ContainerRegistry/registries/BolsaDeTrabajoContainerRegistry"}'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Run services'